const express = require('express');
const { OpenAI } = require('openai');
const router = express.Router();

// In a real implementation, this would connect to a vector database like ChromaDB
// For this example, using a simple in-memory store for demonstration
let mockVectorStore = [
  {
    id: '1',
    content: 'Introduction to Physical AI and Humanoid Robotics',
    embedding: [0.1, 0.2, 0.3], // Simplified embedding
    metadata: { source: 'intro.md', chapter: 'Introduction' }
  },
  {
    id: '2',
    content: 'The Robotic Nervous System (ROS 2) - comprehensive guide to ROS 2 concepts',
    embedding: [0.4, 0.5, 0.6],
    metadata: { source: 'chapter1/index.md', chapter: 'Chapter 1' }
  },
  {
    id: '3', 
    content: 'rclpy bridges for connecting Python with ROS 2',
    embedding: [0.7, 0.8, 0.9],
    metadata: { source: 'chapter1/rclpy-bridges.md', chapter: 'Chapter 1'}
  },
  {
    id: '4',
    content: 'URDF Models: representing humanoid robot structure',
    embedding: [0.2, 0.3, 0.4],
    metadata: { source: 'chapter1/urdf-models.md', chapter: 'Chapter 1' }
  },
  {
    id: '5',
    content: 'Safety principles in ROS 2 for humanoid robotics',
    embedding: [0.5, 0.6, 0.7],
    metadata: { source: 'chapter1/safety-principles.md', chapter: 'Chapter 1' }
  }
];

// Calculate cosine similarity between two vectors
function cosineSimilarity(vecA, vecB) {
  const dotProduct = vecA.reduce((sum, val, idx) => sum + val * vecB[idx], 0);
  const magnitudeA = Math.sqrt(vecA.reduce((sum, val) => sum + val * val, 0));
  const magnitudeB = Math.sqrt(vecB.reduce((sum, val) => sum + val * val, 0));
  
  if (magnitudeA === 0 || magnitudeB === 0) return 0;
  
  return dotProduct / (magnitudeA * magnitudeB);
}

// Simple embedding function for demo purposes
// In a real implementation, this would call a proper embedding API
function getEmbedding(text) {
  // This is a mock embedding function
  // In reality, this would use a model like OpenAI's embeddings API
  const simpleHash = (str) => {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      const char = str.charCodeAt(i);
      hash = (hash << 5) - hash + char;
      hash |= 0; // Convert to 32bit integer
    }
    return hash;
  };
  
  const hash = simpleHash(text);
  return [
    Math.abs(hash) % 1000 / 1000,
    Math.abs(hash * 2) % 1000 / 1000, 
    Math.abs(hash * 3) % 1000 / 1000
  ];
}

// RAG search endpoint
router.post('/search', async (req, res) => {
  try {
    const { query, topK = 5 } = req.body;
    
    if (!query) {
      return res.status(400).json({ error: 'Query parameter is required' });
    }
    
    // Get embedding for the query
    const queryEmbedding = getEmbedding(query);
    
    // Calculate similarity with all stored embeddings
    const similarities = mockVectorStore.map(item => {
      const similarity = cosineSimilarity(queryEmbedding, item.embedding);
      return {
        id: item.id,
        content: item.content,
        similarity,
        metadata: item.metadata
      };
    });
    
    // Sort by similarity (descending) and take top K
    const results = similarities
      .sort((a, b) => b.similarity - a.similarity)
      .slice(0, topK);
    
    res.json({
      query,
      results,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    console.error('Search error:', error);
    res.status(500).json({ error: 'Search failed', message: error.message });
  }
});

// RAG chat endpoint
router.post('/chat', async (req, res) => {
  try {
    const { message, history = [], sessionId } = req.body;
    
    if (!message) {
      return res.status(400).json({ error: 'Message is required' });
    }
    
    // Find relevant content using RAG
    const searchResults = await performRAGSearch(message);
    
    // Create context from search results
    const context = searchResults.map(r => r.content).join('\n\n');
    
    // Generate response using OpenAI API
    let response = '';
    let sources = searchResults.slice(0, 3); // Top 3 sources
    
    // In a real implementation, we would call OpenAI here
    // For this example, we'll generate a mock response
    if (process.env.OPENAI_API_KEY) {
      // This is where you would actually call the OpenAI API
      // For now, using mock response
      response = `This is a mock response based on the context: "${context.substring(0, 200)}...". In a real implementation, this would be generated by an LLM based on the retrieved information.`;
    } else {
      response = `Based on the documentation, here's what I found: ${context.substring(0, 200)}... [Note: OpenAI API key not configured, showing mock response]`;
    }
    
    res.json({
      message,
      response,
      sources,
      sessionId: sessionId || 'default-session',
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    console.error('Chat error:', error);
    res.status(500).json({ error: 'Chat failed', message: error.message });
  }
});

async function performRAGSearch(query) {
  // This would be the actual RAG search logic
  const queryEmbedding = getEmbedding(query);
  
  const similarities = mockVectorStore.map(item => {
    const similarity = cosineSimilarity(queryEmbedding, item.embedding);
    return {
      id: item.id,
      content: item.content,
      similarity,
      metadata: item.metadata
    };
  });
  
  // Sort by similarity (descending)
  return similarities.sort((a, b) => b.similarity - a.similarity);
}

module.exports = router;